const INITIAL_LOGO_SCALE = 0.3;
const FINAL_LOGO_SCALE = 1;
const BACKGROUND_FADE_DURATION = 800;
const LOGO_FADE_DURATION = 1200;
const SPLASH_SCREEN_DURATION = 3000;

export {
  INITIAL_LOGO_SCALE,
  FINAL_LOGO_SCALE,
  BACKGROUND_FADE_DURATION,
  LOGO_FADE_DURATION,
  SPLASH_SCREEN_DURATION,
};
